## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Carnarvon,AU,-24.8667,113.6333,104.07,6,0,17.27,clear sky,2021-11-26 04:53:10
1,1,Kodiak,US,57.7900,-152.4072,15.31,62,40,21.85,scattered clouds,2021-11-26 04:53:10
2,2,Port Lincoln,AU,-34.7333,135.8667,61.93,52,85,18.37,overcast clouds,2021-11-26 04:53:11
3,3,West Bay,KY,19.3667,-81.4167,80.01,78,57,3.00,broken clouds,2021-11-26 04:53:11
4,4,Bathsheba,BB,13.2167,-59.5167,77.61,94,75,5.75,broken clouds,2021-11-26 04:53:12

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input('What is the minimum temperature you would like for your trip? '))
max_temp = float(input('What is the maximum temperature you would like for your trip? '))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
clean_df = city_data_df.loc[(city_data_df['Max Temp'] <= max_temp) & \
                                       (city_data_df['Max Temp'] >= min_temp)]
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
3,3,West Bay,KY,19.3667,-81.4167,80.01,78,57,3.00,broken clouds,2021-11-26 04:53:11
4,4,Bathsheba,BB,13.2167,-59.5167,77.61,94,75,5.75,broken clouds,2021-11-26 04:53:12
13,13,Axim,GH,4.8699,-2.2405,78.75,84,32,6.29,scattered clouds,2021-11-26 04:53:15
19,19,Rikitea,PF,-23.1203,-134.9692,76.48,78,17,11.74,light rain,2021-11-26 04:53:18
25,25,Tezu,IN,27.9167,96.1667,76.53,36,84,3.44,broken clouds,2021-11-26 04:53:21
...,...,...,...,...,...,...,...,...,...,...,...
687,687,Kadhan,PK,24.4810,68.9859,82.53,24,0,2.55,clear sky,2021-11-26 04:57:55
690,690,Anito,PH,12.4497,125.2886,82.65,81,92,7.92,overcast clouds,2021-11-26 04:57:56
696,696,Luganville,VU,-15.5333,167.1667,82.74,70,7,10.27,clear sky,2021-11-26 04:57:59
698,698,Araguari,BR,-18.6472,-48.1872,77.29,62,99,3.47,overcast clouds,2021-11-26 04:54:00
699,699,Moerai,PF,-22.4333,-151.3333,78.19,83,3,6.89,clear sky,2021-11-26 04:58:00

In [5]:
# 4a. Determine if there are any empty rows.
clean_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
hotel_df = clean_df.dropna()
hotel_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
3,3,West Bay,KY,19.3667,-81.4167,80.01,78,57,3.00,broken clouds,2021-11-26 04:53:11
4,4,Bathsheba,BB,13.2167,-59.5167,77.61,94,75,5.75,broken clouds,2021-11-26 04:53:12
13,13,Axim,GH,4.8699,-2.2405,78.75,84,32,6.29,scattered clouds,2021-11-26 04:53:15
19,19,Rikitea,PF,-23.1203,-134.9692,76.48,78,17,11.74,light rain,2021-11-26 04:53:18
25,25,Tezu,IN,27.9167,96.1667,76.53,36,84,3.44,broken clouds,2021-11-26 04:53:21
...,...,...,...,...,...,...,...,...,...,...,...
687,687,Kadhan,PK,24.4810,68.9859,82.53,24,0,2.55,clear sky,2021-11-26 04:57:55
690,690,Anito,PH,12.4497,125.2886,82.65,81,92,7.92,overcast clouds,2021-11-26 04:57:56
696,696,Luganville,VU,-15.5333,167.1667,82.74,70,7,10.27,clear sky,2021-11-26 04:57:59
698,698,Araguari,BR,-18.6472,-48.1872,77.29,62,99,3.47,overcast clouds,2021-11-26 04:54:00
699,699,Moerai,PF,-22.4333,-151.3333,78.19,83,3,6.89,clear sky,2021-11-26 04:58:00

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,West Bay,KY,80.01,broken clouds,19.3667,-81.4167,
4,Bathsheba,BB,77.61,broken clouds,13.2167,-59.5167,
13,Axim,GH,78.75,scattered clouds,4.8699,-2.2405,
19,Rikitea,PF,76.48,light rain,-23.1203,-134.9692,
25,Tezu,IN,76.53,broken clouds,27.9167,96.1667,
41,Tanete,ID,89.37,overcast clouds,-3.9443,119.7848,
47,Cabo San Lucas,MX,75.51,overcast clouds,22.8909,-109.9124,
51,Teahupoo,PF,78.76,clear sky,-17.8333,-149.2667,
52,Sola,VU,81.27,few clouds,-13.8833,167.5500,
53,Gabas,PH,83.77,overcast clouds,10.7297,124.7961,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    hotels

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df = hotel_df.dropna()
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,West Bay,KY,80.01,broken clouds,19.3667,-81.4167,
4,Bathsheba,BB,77.61,broken clouds,13.2167,-59.5167,
13,Axim,GH,78.75,scattered clouds,4.8699,-2.2405,
19,Rikitea,PF,76.48,light rain,-23.1203,-134.9692,
25,Tezu,IN,76.53,broken clouds,27.9167,96.1667,
...,...,...,...,...,...,...,...
687,Kadhan,PK,82.53,clear sky,24.4810,68.9859,
690,Anito,PH,82.65,overcast clouds,12.4497,125.2886,
696,Luganville,VU,82.74,clear sky,-15.5333,167.1667,
698,Araguari,BR,77.29,overcast clouds,-18.6472,-48.1872,
699,Moerai,PF,78.19,clear sky,-22.4333,-151.3333,

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))